{"content": {"suites": {"0": {"status": {"total_pass": 1, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 1, "total_error": 0}, "tests": {"0": {"status": "PASS", "message": "", "test_name": "test_add_new_student", "rerun": "0"}, "1": {"status": "FAIL", "message": "   socket.gaierror: [Errno 11001] getaddrinfo failed\n       urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x000002640C7F2510>: Failed to resolve 'thetestingworld' ([Errno 11001] getaddrinfo failed)\n       urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='thetestingworld', port=443): Max retries exceeded with url: /api/studentsDetails/%3Cbuilt-in%20function%20id%3E (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x000002640C7F2510>: Failed to resolve 'thetestingworld' ([Errno 11001] getaddrinfo failed)\"))\n       requests.exceptions.ConnectionError: HTTPSConnectionPool(host='thetestingworld', port=443): Max retries exceeded with url: /api/studentsDetails/%3Cbuilt-in%20function%20id%3E (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x000002640C7F2510>: Failed to resolve 'thetestingworld' ([Errno 11001] getaddrinfo failed)\"))\n", "test_name": "test_get_student_detail", "rerun": "0"}}, "suite_name": "test_request_chaining.py"}}}, "date": "July 04, 2024", "start_time": 1720087864.0870903, "total_suite": 1, "status": "FAIL", "status_list": {"pass": "1", "fail": "1", "skip": "0", "error": "0", "xpass": "0", "xfail": "0", "rerun": "0"}, "total_tests": "2"}